'use strict';
// Gift-specific enhancement: retain native form values, replace browser popup UI.
(()=>{
  const widgets=new WeakMap();let active=null,serial=0;
  const pad=n=>String(n).padStart(2,'0');
  function close(focus=false){if(!active)return;const {button,popup}=active;active=null;button.setAttribute('aria-expanded','false');button.removeAttribute('aria-controls');popup.remove();if(focus&&button.isConnected)button.focus();}
  function popupFor(button,kind){close();const popup=document.createElement('div');popup.className='gift-picker '+kind;popup.id='gift-picker-'+(++serial);popup.setAttribute('popover','manual');popup.setAttribute('role',kind==='choice-picker'?'listbox':'dialog');popup.setAttribute('aria-label',button.getAttribute('aria-label'));(button.closest('dialog[open]')||document.body).append(popup);button.setAttribute('aria-expanded','true');button.setAttribute('aria-controls',popup.id);active={button,popup};popup.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();close(true);}else if(e.key==='Tab'&&kind==='choice-picker'){close(true);}});return popup;}
  function position(popup,button){popup.showPopover();const r=button.getBoundingClientRect(),w=innerWidth,h=innerHeight;popup.style.width=Math.min(Math.max(r.width,popup.classList.contains('date-picker')?300:220),w-24)+'px';const below=h-r.bottom-16,above=r.top-16,up=below<320&&above>below;popup.style.maxHeight=Math.max(80,Math.min(420,up?above:below))+'px';popup.style.left=Math.max(12,Math.min(r.left,w-popup.offsetWidth-12))+'px';popup.style.top=(up?Math.max(12,r.top-popup.offsetHeight-6):r.bottom+6)+'px';}
  function setValue(input,value){input.value=value;widgets.get(input).sync();close(true);input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));}
  function choice(select,button){const popup=popupFor(button,'choice-picker');const search=document.createElement('input');search.type='search';search.placeholder='搜索选项';search.setAttribute('aria-label','搜索选项');search.className='picker-search';const list=document.createElement('div');popup.append(search,list);
    function render(){list.replaceChildren();[...select.options].forEach((option,index)=>{if(!option.textContent.toLowerCase().includes(search.value.toLowerCase()))return;const item=document.createElement('button');item.type='button';item.className='picker-option';item.setAttribute('role','option');item.setAttribute('aria-selected',String(option.selected));item.disabled=option.disabled;const label=document.createElement('span'),mark=document.createElement('span');label.textContent=option.textContent;mark.textContent=option.selected?'✓':'';item.append(label,mark);item.onclick=()=>{select.selectedIndex=index;widgets.get(select).sync();close(true);select.dispatchEvent(new Event('change',{bubbles:true}));};list.append(item);});if(!list.childElementCount){const p=document.createElement('p');p.className='muted';p.textContent='没有匹配的选项';list.append(p);}}
    search.oninput=render;render();position(popup,button);search.focus({preventScroll:true});popup.onkeydown=e=>{const buttons=[...list.querySelectorAll('button:not(:disabled)')],index=buttons.indexOf(document.activeElement);if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?buttons.length-1:Math.max(0,Math.min(buttons.length-1,index+(e.key==='ArrowDown'?1:-1)));buttons[next]?.focus();}};
  }
  function calendar(input,button){const monthOnly=input.type==='month';let parts=(input.value||new Date().getFullYear()+'-'+pad(new Date().getMonth()+1)).split('-').map(Number),year=parts[0],month=parts[1]-1;const popup=popupFor(button,'date-picker');
    function draw(){popup.replaceChildren();const head=document.createElement('div');head.className='calendar-head';const prev=document.createElement('button'),next=document.createElement('button'),title=document.createElement('div');prev.type=next.type='button';prev.textContent='‹';next.textContent='›';prev.setAttribute('aria-label',monthOnly?'上一年':'上一月');next.setAttribute('aria-label',monthOnly?'下一年':'下一月');const yearInput=document.createElement('input');yearInput.type='number';yearInput.min=1;yearInput.max=9999;yearInput.value=year;yearInput.setAttribute('aria-label','年份');const suffix=document.createElement('span');suffix.textContent=monthOnly?'年':`年 ${month+1}月`;title.append(yearInput,suffix);head.append(prev,title,next);popup.append(head);yearInput.onchange=()=>{const n=Number(yearInput.value);if(Number.isInteger(n)&&n>=1&&n<=9999){year=n;draw();}else yearInput.value=year;};const move=delta=>{if(monthOnly)year+=delta;else{month+=delta;if(month<0){month=11;year--;}if(month>11){month=0;year++;}}year=Math.max(1,Math.min(9999,year));draw();};prev.onclick=()=>move(-1);next.onclick=()=>move(1);
      const grid=document.createElement('div');grid.className=monthOnly?'month-grid':'day-grid';popup.append(grid);const prefix=String(year).padStart(4,'0');
      function cell(text,value){const b=document.createElement('button');b.type='button';b.textContent=text;b.setAttribute('aria-label',value);b.className='calendar-cell';const selected=input.value===value;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected));b.disabled=!!((input.min&&value<input.min)||(input.max&&value>input.max));b.onclick=()=>setValue(input,value);grid.append(b);}
      if(monthOnly){for(let m=1;m<=12;m++)cell(m+'月',prefix+'-'+pad(m));}else{for(const day of ['一','二','三','四','五','六','日']){const s=document.createElement('span');s.className='weekday';s.textContent=day;grid.append(s);}const start=new Date(0);start.setFullYear(year,month,1);for(let i=0;i<(start.getDay()+6)%7;i++)grid.append(document.createElement('span'));const end=new Date(0);end.setFullYear(year,month+1,0);for(let d=1;d<=end.getDate();d++)cell(d,prefix+'-'+pad(month+1)+'-'+pad(d));}
      const foot=document.createElement('div');foot.className='calendar-foot';const today=document.createElement('button'),clear=document.createElement('button');today.type=clear.type='button';today.textContent=monthOnly?'本月':'今天';clear.textContent='清空';const now=new Date(),value=now.getFullYear()+'-'+pad(now.getMonth()+1)+(monthOnly?'':'-'+pad(now.getDate()));today.disabled=!!((input.min&&value<input.min)||(input.max&&value>input.max));today.onclick=()=>setValue(input,value);clear.onclick=()=>setValue(input,'');foot.append(today,clear);popup.append(foot);}
    popup.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)||!document.activeElement.classList.contains('calendar-cell'))return;e.preventDefault();const cells=[...popup.querySelectorAll('.calendar-cell')],index=cells.indexOf(document.activeElement),step=e.key==='ArrowLeft'?-1:e.key==='ArrowRight'?1:(e.key==='ArrowUp'?-1:1)*(monthOnly?3:7);cells[Math.max(0,Math.min(cells.length-1,index+step))]?.focus();});
    draw();position(popup,button);popup.querySelector('.selected:not(:disabled)')?.focus({preventScroll:true});if(!popup.contains(document.activeElement))popup.querySelector('button').focus({preventScroll:true});
  }
  function enhance(input){if(widgets.has(input)||input.multiple)return;const isSelect=input.tagName==='SELECT',button=document.createElement('button');button.type='button';button.className='control-trigger '+(isSelect?'select-trigger':'date-trigger');button.setAttribute('aria-label',input.getAttribute('aria-label')||input.closest('label')?.childNodes[0]?.textContent.trim()||'选择');button.setAttribute('aria-haspopup',isSelect?'listbox':'dialog');button.setAttribute('aria-expanded','false');const label=document.createElement('span'),mark=document.createElement('span');mark.className='control-mark';mark.textContent=isSelect?'⌄':'▦';mark.setAttribute('aria-hidden','true');button.append(label,mark);input.after(button);input.hidden=true;
    const sync=()=>{const value=isSelect?(input.selectedOptions[0]?.textContent||'请选择'):(input.value?(input.type==='month'?input.value.replace('-','年')+'月':input.value.replace('-','年').replace('-','月')+'日'):(input.type==='month'?'选择月份':'选择日期'));if(label.textContent!==value)label.textContent=value;button.disabled=input.disabled;button.classList.toggle('empty-value',!input.value);};widgets.set(input,{sync,button});sync();input.addEventListener('change',sync);button.onclick=()=>{if(active?.button===button)close();else isSelect?choice(input,button):calendar(input,button);};button.onkeydown=e=>{if(e.key==='ArrowDown'){e.preventDefault();button.click();}};
  }
  function scan(){if(active&&!active.button.isConnected)close();document.querySelectorAll('select,input[type="date"],input[type="month"]').forEach(input=>{enhance(input);widgets.get(input)?.sync();});}
  new MutationObserver(scan).observe(document.documentElement,{childList:true,subtree:true});document.addEventListener('change',scan);document.addEventListener('pointerdown',e=>{if(active&&!active.popup.contains(e.target)&&!active.button.contains(e.target))close();},true);document.addEventListener('scroll',e=>{if(active&&!active.popup.contains(e.target)){const current=active;requestAnimationFrame(()=>{if(active===current)position(current.popup,current.button);});}},true);document.addEventListener('close',()=>close(),true);window.addEventListener('resize',()=>close());scan();
})();
