'use strict';
(async()=>{
  const {$,esc,icon,fileIcon,refreshIcons,size,date,api,toast,preview}=FS;
  const code=location.pathname.replace(/\/$/,'').split('/').pop();
  const base='/api/file-share/public/'+encodeURIComponent(code);let share;
  function failed(message){$('publicContent').innerHTML=`<div class="password-card">${icon('link-2-off')}<h1>分享不可用</h1><p class="muted">${esc(message)}</p></div>`;refreshIcons();}
  function passwordForm(){
    $('publicContent').innerHTML=`<form id="passwordForm" class="password-card"><span class="brand-mark">${icon('lock-keyhole')}</span><h1>这份分享已加密</h1><p class="muted">请输入分享者提供的密码，查看文件。</p><label>访问密码<input id="sharePassword" type="password" minlength="4" maxlength="128" autocomplete="off" required autofocus placeholder="输入分享密码"></label><p id="passwordError" class="inline-error" role="alert"></p><button class="primary">查看文件 ${icon('arrow-right')}</button></form>`;refreshIcons();
    $('passwordForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{share=await api(base+'/password',{password:$('sharePassword').value});render();}catch(error){if(error.status===410)failed(error.message);else{$('passwordError').textContent=error.message;button.disabled=false;}}};
  }
  function render(){document.title=share.title+' · 文件分享中心';$('publicContent').innerHTML=`<section class="public-intro"><p class="eyebrow">SHARED WITH YOU</p><h1>${esc(share.title)}</h1>${share.description?`<p class="description">${esc(share.description)}</p>`:''}<div class="public-meta">${share.display_name?`<span>${esc(share.display_name)} 分享</span>`:''}<span>${share.files.length} 个文件</span><span>${date(share.expires_at)}${share.expires_at?' 到期':''}</span></div></section><section class="public-files">${share.files.length?share.files.map(f=>`<div class="list-row">${fileIcon(f)}<div class="list-main"><strong>${esc(f.filename)}</strong><small>${size(f.size)} · ${esc(f.file_type)}</small></div><div class="actions">${share.allow_preview&&['IMAGE','VIDEO','AUDIO','PDF','TEXT'].includes(f.file_type)?`<button data-file="${f.id}" data-action="preview">${icon('eye')}预览</button>`:share.allow_preview?'<small>暂不支持在线预览，请下载查看</small>':''}${share.allow_download?`<button class="primary" data-file="${f.id}" data-action="download">${icon('download')}下载</button>`:''}</div></div>`).join(''):'<div class="empty"><p>分享中的文件已被移除。</p></div>'}</section>`;refreshIcons();
    $('publicContent').onclick=async e=>{const button=e.target.closest('[data-action]');if(!button)return;const file=share.files.find(f=>f.id===button.dataset.file);button.disabled=true;try{const result=await api(base+'/'+button.dataset.action,{file_id:file.id});if(button.dataset.action==='preview')await preview(file,result.url);else{const a=document.createElement('a');a.href=result.url;a.rel='noopener noreferrer';document.body.append(a);a.click();a.remove();}}catch(error){if(error.status===401)passwordForm();else toast(error.message);}finally{button.disabled=false;}};
  }
  try{const challenge=await api(base);try{share=await api(base+'/open',{});render();}catch(error){if(error.status===401&&challenge.password_required)passwordForm();else failed(error.message);}}catch(error){failed(error.message);}
})();
